### ISSUE TITLE
Captcha test

### ISSUE THREAD

**Issue by shailesh** [bombardier-gif/covid-vaccine-booking#153]
```
Opening test window. Click on "Quit" to run further tests
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Failed to load input file! (Document is empty, line 1, column 1 (captcha.svg, line 1))
Traceback (most recent call last):
  File "tests/captcha_tests.py", line 99, in <module>
    test_captcha_builder()
  File "tests/captcha_tests.py", line 11, in test_captcha_builder
    renderPM.drawToFile(drawing, "captcha.png", fmt="PNG")
  File "/Users/shailesh14.singh/Documents/scripts/covid-vaccine-booking/venv/lib/python3.8/site-packages/reportlab/graphics/renderPM.py", line 692, in drawToFile
    c = drawToPMCanvas(d, dpi=dpi, bg=bg, configPIL=configPIL, showBoundary=showBoundary,backend=backend)
  File "/Users/shailesh14.singh/Documents/scripts/covid-vaccine-booking/venv/lib/python3.8/site-packages/reportlab/graphics/renderPM.py", line 676, in drawToPMCanvas
    d = renderScaledDrawing(d)
  File "/Users/shailesh14.singh/Documents/scripts/covid-vaccine-booking/venv/lib/python3.8/site-packages/reportlab/graphics/renderbase.py", line 153, in renderScaledDrawing
    renderScale = d.renderScale
AttributeError: 'NoneType' object has no attribute 'renderScale'

```

**Comment by bombardier-gif** [comment]
I think there is  a problem with versions. Please install the latest version of tk and try again. 
Reopen this issue if it still exists
