### ISSUE TITLE
Issue While trying to deploy on heroku

### ISSUE THREAD

**Issue by MrAnkit007** [bombardier-gif/covid-vaccine-booking#36]
python3 script.py
Traceback (most recent call last):
  File "/app/script.py", line 9, in <module>
    from utils import generate_token_OTP, check_and_book, beep, BENEFICIARIES_URL, WARNING_BEEP_DURATION, \
  File "/app/utils.py", line 6, in <module>
    from captcha import captcha_builder
  File "/app/captcha.py", line 3, in <module>
    import PySimpleGUI as sg
  File "/app/.heroku/python/lib/python3.9/site-packages/PySimpleGUI/__init__.py", line 2, in <module>
    from .PySimpleGUI import *
  File "/app/.heroku/python/lib/python3.9/site-packages/PySimpleGUI/PySimpleGUI.py", line 95, in <module>
    import tkinter as tk
  File "/app/.heroku/python/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

PS: I even tried to renamed the main covac-vaccine-slot-booking.py to script.py

minor tweaked repo link https://github.com/MrAnkit007/covac.git

**Comment by bombardier-gif** [comment]
i got this error too i mitigated it by installing  tk using this command in mac
brew install python-tk

Please find the appropriate linux command and install. Also please update the readme for others :)

**Comment by bombardier-gif** [comment]
Also tk version could be an issue some had faced it yesterday

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
