### ISSUE TITLE
Getting ModuleNotFoundError: No module named 'inputimeout' on Macbook

### ISSUE THREAD

**Issue by Sheshgiriv** [bombardier-gif/covid-vaccine-booking#446]
I'm trying to book a slot getting the below timeout error , please look into this. 

```
➜  covid-vaccine-booking git:(heads/main) python3 src/covid-vaccine-slot-booking.py
Traceback (most recent call last):
  File "src/covid-vaccine-slot-booking.py", line 8, in <module>
    from utils import generate_token_OTP, generate_token_OTP_manual, check_and_book, beep, BENEFICIARIES_URL, WARNING_BEEP_DURATION, \
  File "/Users/venkateshsheshgiri/Cowin/covid-vaccine-booking/src/utils.py", line 4, in <module>
    from inputimeout import inputimeout, TimeoutOccurred
ModuleNotFoundError: No module named 'inputimeout'
```

**Comment by Sheshgiriv** [comment]
Installed the below modules its working now 

pip install inputtimeout
pip install tabulate
pip install svglib
pip install PySimpleGUI
pip install bs4

**Comment by bombardier-gif** [comment]
Thanks for pasting the solution too
