### ISSUE TITLE
Latest code failing and not running through Python Script

### ISSUE THREAD

**Issue by jishnu-gv** [bombardier-gif/covid-vaccine-booking#74]
Traceback (most recent call last):
  File "C:\Users\jishn\OneDrive\Desktop\Ramesh-Personal\Ramesh-Python-Selenium\covid-vaccine-booking\src\covid-vaccine-slot-booking.py", line 6, in <module>
    from utils import generate_token_OTP, generate_token_OTP_manual, check_and_book, beep, BENEFICIARIES_URL, WARNING_BEEP_DURATION, \
  File "C:\Users\jishn\OneDrive\Desktop\Ramesh-Personal\Ramesh-Python-Selenium\covid-vaccine-booking\src\utils.py", line 6, in <module>
    from captcha import captcha_builder, captcha_builder_auto
  File "C:\Users\jishn\OneDrive\Desktop\Ramesh-Personal\Ramesh-Python-Selenium\covid-vaccine-booking\src\captcha.py", line 6, in <module>
    from anticaptchaofficial.imagecaptcha import imagecaptcha
ModuleNotFoundError: No module named 'anticaptchaofficial'

**Comment by bombardier-gif** [comment]
@dhavalsavalia Please take a look here

**Comment by bombardier-gif** [comment]
just install the module anticaptchaofficial
either
 python3 -m pip install anticaptchaofficial
or
pip install anticaptchaofficial
